# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=500)),
                ('paddress', models.CharField(max_length=500)),
                ('education', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('hacker', models.CharField(max_length=50)),
                ('linkdin', models.CharField(max_length=50)),
                ('git', models.CharField(max_length=50)),
                ('blog', models.CharField(max_length=500)),
            ],
        ),
    ]
